## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]

# Display a sample of y_df
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    "Education", "Age", "DistanceFromHome", "JobSatisfaction",
    "OverTime", "StockOptionLevel", "WorkLifeBalance",
    "YearsAtCompany", "YearsSinceLastPromotion", "NumCompaniesWorked"
]

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [5]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

# Display the shapes of the training and testing sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (1176, 10)
X_test shape: (294, 10)
y_train shape: (1176, 2)
y_test shape: (294, 2)


In [6]:
# Convert the 'OverTime' column to numeric by mapping 'Yes' to 1 and 'No' to 0
X_df["OverTime"] = X_df["OverTime"].map({"Yes": 1, "No": 0})

# Verify the conversion by checking value counts
print(X_df["OverTime"].value_counts())


OverTime
0    1054
1     416
Name: count, dtype: int64


C:\Users\Coding Guru\AppData\Local\Temp\ipykernel_12344\2952505424.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df["OverTime"] = X_df["OverTime"].map({"Yes": 1, "No": 0})


In [8]:
# Convert categorical columns to numeric using one-hot encoding
X_df_encoded = pd.get_dummies(X_df)

# Split the encoded data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df_encoded, y_df, test_size=0.2, random_state=42)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Display a sample of the scaled training data
print(X_train_scaled[:5])


[[-0.86335572 -1.38855944  1.44039645 -1.58233648 -0.63641018  2.54747106
   0.3574354  -0.97426331 -0.67610953 -1.05916816]
 [-0.86335572 -2.04073779 -0.52269928  1.15283407 -0.63641018 -0.94552463
   0.3574354  -1.13857331 -0.67610953 -0.65943075]
 [-0.86335572 -0.84507748  1.31770296  1.15283407 -0.63641018  0.21880727
   0.3574354  -0.6456433  -0.67610953 -0.25969335]
 [ 0.09993302  0.24188644  0.3361551  -0.67061296 -0.63641018 -0.94552463
   0.3574354  -0.3170233  -0.35524399  0.53978146]
 [ 0.09993302 -0.62768469  1.31770296  0.24111056 -0.63641018  0.21880727
   0.3574354   0.50452672 -0.67610953 -0.65943075]]


In [10]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the Department column in the training data
encoder.fit(y_train[["Department"]])

# Apply the encoder to the Department column in the training and testing data
department_train_encoded = encoder.transform(y_train[["Department"]])
department_test_encoded = encoder.transform(y_test[["Department"]])

# Display a sample of the encoded training data
print(department_train_encoded[:5])


[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [11]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the Attrition column in the training data
attrition_encoder.fit(y_train[["Attrition"]])

# Apply the encoder to the Attrition column in the training and testing data
attrition_train_encoded = attrition_encoder.transform(y_train[["Attrition"]])
attrition_test_encoded = attrition_encoder.transform(y_test[["Attrition"]])

# Display a sample of the encoded training data
print(attrition_train_encoded[:5])


[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [12]:
from tensorflow.keras import Input
from tensorflow.keras.layers import Dense

# Find the number of columns in the X training data
input_dim = X_train_scaled.shape[1]
print("Number of input features:", input_dim)

# Create the input layer
input_layer = Input(shape=(input_dim,))

# Create at least two shared layers with ReLU activation
shared_layer1 = Dense(64, activation='relu')(input_layer)
shared_layer2 = Dense(32, activation='relu')(shared_layer1)

# Display the shared layers to confirm their creation
print("Shared layers created.")


Number of input features: 10
Shared layers created.


In [13]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer for the Department branch
department_hidden_layer = Dense(16, activation='relu')(shared_layer2)

# Create the output layer for the Department branch
department_output = Dense(department_train_encoded.shape[1], activation='softmax', name="Department_Output")(department_hidden_layer)


In [14]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer for the Attrition branch
attrition_hidden_layer = Dense(16, activation='relu')(shared_layer2)

# Create the output layer for the Attrition branch
attrition_output = Dense(attrition_train_encoded.shape[1], activation='softmax', name="Attrition_Output")(attrition_hidden_layer)


In [30]:
from tensorflow.keras.models import Model

# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

# Summarize the model
model.summary()


Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Department_Output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Attrition_Output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
from tensorflow.keras.models import Model

# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

# Summarize the model
model.summary()


Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Department_Output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Attrition_Output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# Define the model layers again to ensure correct output shapes
from tensorflow.keras.models import Model

# Department branch
department_hidden_layer = Dense(16, activation='relu')(shared_layer2)
department_output = Dense(3, activation='softmax', name="Department_Output")(department_hidden_layer)  # 3 neurons

# Attrition branch
attrition_hidden_layer = Dense(16, activation='relu')(shared_layer2)
attrition_output = Dense(2, activation='softmax', name="Attrition_Output")(attrition_hidden_layer)  # 2 neurons

# Create and compile the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

# Display model summary to confirm output shapes
model.summary()


Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 16)        │      2,064 │ shared2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 16)        │      2,064 │ shared2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Department_Output   │ (None, 3)         │         51 │ dense_8[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Attrition_Output    │ (None, 2)         │         34 │ dense_9[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 13,237 (51.71 KB)

 Trainable params: 13,237 (51.71 KB)

 Non-trainable params: 0 (0.00 B)

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy may not be the best metric if the dataset is imbalanced, meaning that one class (e.g., “no attrition”) has significantly more instances than another (e.g., “attrition”). In cases of imbalance, accuracy can be misleading, as the model may predict the majority class more frequently to achieve high accuracy, without effectively identifying the minority class. Alternative metrics like precision, recall, and F1 score could provide more insight into the model’s performance, especially in identifying the less frequent class.

2. For the output layers, I used the softmax activation function for both Department_Output and Attrition_Output. The softmax function is suitable for multi-class and binary classification tasks, as it outputs probabilities for each class, allowing the model to make a probabilistic prediction. This is particularly useful for interpreting the confidence of each prediction, which is essential when distinguishing among multiple categories in a classification task.

3. Hyperparameter Tuning: Adjusting parameters such as the number of layers, neurons per layer, batch size, and learning rate could improve model performance.
Experiment with Other Architectures: Testing other architectures, such as Convolutional Neural Networks (if there’s spatial data) or Recurrent Neural Networks (for sequential data), could yield better results depending on the data characteristics.
Use Class Weights or Sampling Techniques: If the dataset is imbalanced, using class weights or oversampling the minority class can help the model pay more attention to the less frequent classes.
Add Regularization: Implementing techniques like dropout or L2 regularization can help prevent overfitting, especially if the dataset is small or prone to noise.
Explore Ensemble Methods: Combining predictions from multiple models or architectures (e.g., ensemble learning) can improve robustness and accuracy by leveraging strengths across models. 